services:
  - type: web
    name: mastnger
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python init_database.py && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: RENDER
        value: true
